### ISSUE TITLE
启动项目很久

### ISSUE THREAD

**Issue by 0131LWG** [meooxx/uniapp-project-cli#2]
目前启动项目非常的久，并且会报错Cannot find module 'stylus'
![image](https://user-images.githubusercontent.com/30310735/123588387-40a16380-d81a-11eb-8ca3-146cdf56d935.png)
已经安装了stylus依赖，但依然报错
![image](https://user-images.githubusercontent.com/30310735/123588457-5f9ff580-d81a-11eb-962a-d8c03f9e890a.png)

**Comment by meooxx** [comment]
1 要fork 后 安装在 dependencies 下面。 因为devDependecies 上，npm install -g 后不会安装devDependecies， 这个是npm 的使用问题。
2 我这个工具， 跟直接使用 vue-cli 没什么区别的, 启动速度优化，请从常规打包优化方案方面解决。

**Comment by 0131LWG** [comment]
> 1 要fork后安装在依赖项下面。因为devDependies上，npm install -g 后不会安装devDependies，这是npm的使用问题。
> 2 我的工具，跟直接使用vue-cli没什么区别，启动优化优化，请从优化打包优化方案方面解决。

谢谢，目前知道原因了我在webpack中配置了压缩代码，所以启动就会很久，还有一个问题，目前是将文件都放在根目录下，在app开发中能否使用nativeplugins原生插件呢？

**Comment by meooxx** [comment]
> > 1 要fork后安装在依赖项下面。因为devDependies上，npm install -g 后不会安装devDependies，这是npm的使用问题。
> 
> > 2 我的工具，跟直接使用vue-cli没什么区别，启动优化优化，请从优化打包优化方案方面解决。
> 
> 
> 
> 谢谢，目前知道原因了我在webpack中配置了压缩代码，所以启动就会很久，还有一个问题，目前是将文件都放在根目录下，在app开发中能否使用nativeplugins原生插件呢？

1 这个我就不知道了，我只用小程序开发，可以自己尝试试一下
2跟用vue-cli创建的项目一致，vue-cli可以，这个工具就行。
