### ISSUE TITLE
基于若依-ruoyi-AiDex-Uniapp二次开发的uniapp项目启动失败

### ISSUE THREAD

**Issue by lsiuf** [meooxx/uniapp-project-cli#3]
项目参考：https://gitee.com/big-hedgehog/ruoyi-uniapp?_from=gitee_search

异常出现步骤：
0. 已根据提示安装uapp插件
1. unilaunch . -c dev:h5
2. 提示异常信息
![image](https://github.com/meooxx/uniapp-project-cli/assets/44636496/949ff2e1-bb46-4c09-86a6-d2d873eda3f2)

需求：目前uniapp项目无法集成到coding自动化部署流水线中，需要在HbuilderX中打包后上传到服务器再进行部署，现在想将HbuilderX打包H5这一步放到服务器内，实现一键打包部署。

根据网上一些文章，尝试过用vue-cli创建uniapp初始项目然后想HbuilderX中的项目换过去，但启动失败。
后来看到作者的插件想尝试下，跳过手动替换vue-cli项目的步骤，但使用时提示异常。
谢谢！

**Comment by meooxx** [comment]
@lsiuf hi， 你好，根据你的描述，我已在本地成功运行了。
截图中提示sass-loader的依赖（clone-deep）没有找到, 我猜测可能如下原因

1 按我步骤中的描述正确安装 `unilaunch`, 
```npm install -g github:meooxx/uniapp-project-cli```, 如果因为众所周知的原因github网络的问题. 可以 fork 本仓库到其他仓库中（如gitee描述所提到的），再使用npm 从该源码仓库安装

2 另外我在本地复现的发现以下问题，因本项目使用sass的包，导致`/deep`语法不可用，请自行换v::deep的写法，或者更换其他sass的依赖。 这个问题我在教程描述中也有提到

3 运行中发现你提供的项目依赖node为16，请注意降级node版本到16，或者升级项目相关依赖

4 由于uniapp持续升级，可自行升级本项目对应依赖uniapp的相关库。
另外附上我本地运行成功的截图希望能帮助到你

<img width="751" alt="image" src="https://github.com/meooxx/uniapp-project-cli/assets/13815865/4ee1aa92-fcf4-4d53-958e-5a769987e766">
<img width="948" alt="image" src="https://github.com/meooxx/uniapp-project-cli/assets/13815865/fa63d3f3-6f9c-4a9c-92f7-ec71ff833f9d">
